#
# Module manifest for module 'MsGraph'
#
# Generated by: Floris van Enter | EnterMI
#

@{
    # Script module or binary module file associated with this manifest
    RootModule = 'MsGraph.psm1'

    # Version number of this module.
    ModuleVersion = '1.0.0.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID = '1ae26624-2a10-43a6-ba32-3adb7c2be4d5'

    # Author of this module
    Author = 'Floris van Enter'

    # Company or vendor of this module
    CompanyName = 'EnterMI'

    # Copyright statement for this module
    Copyright = '(c) EnterMI. MIT Licensed.'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Minimum version of the common language runtime (CLR) required by this module
    CLRVersion = '4.0'

    # Cmdlets to export from this module
    CmdletsToExport = @(
        'Get-MSGraphGetResponse',
        'Get-MSGraphToken'
        )

    # Aliases to export from this module
    AliasesToExport = @()

    # HelpInfo
    HelpInfoUri = 'https://github.com/florisvanenter/powershell.git'

    }
